-- MySQL Script generated by MySQL Workbench
-- Wed Jan 27 17:43:14 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';


-- -----------------------------------------------------
-- Schema BancoCep
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BancoCep` DEFAULT CHARACTER SET utf8 ;
USE `BancoCep` ;

-- -----------------------------------------------------
-- Table `BancoCep`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BancoCep`.`endereco` (
  `cep` VARCHAR(8) NOT NULL,
  `uf` VARCHAR(2) NOT NULL,
  `cidade` VARCHAR(30) NOT NULL,
  `bairro` VARCHAR(30) NOT NULL,
  `rua` VARCHAR(30) NOT NULL,
  `numero_rua` VARCHAR(4) NOT NULL,
  `complemento` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`cep`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;